### ISSUE TITLE
Proposal for endpoint syntax

### ISSUE THREAD

**Issue by wilmveel** [flock-community/wirespec#16]
To generate openapi specification from wire-spec definitions there needs to be syntax to describe endpoints. 

```
type TodoId {
    id: String
}

type Todo {
    id: TodoId,
    name: String,
    done: Boolean
}

type TodoInput {
    name: String,
    done: Boolean
}

type Error {
    code: String,
    description: String
}

endpoint GetTodos GET /todos?{done: Boolean?} {
    200: Todo[]
    404: Error
}

endpoint GetTodoById GET /todos/{id: Int}  {
    200: Todo
    404: Error
    500: Error
}

endpoint CreateTodo POST /todos/{id: Int}  {
    200: Todo
    404: Error
    500: Error
}

endpoint Update Todo PUT /todos/{id: Int} TodoInput {
    200: Todo
    404: Error
    500: Error
}

endpoint DeleteTodo DELETE /todos/{id: Int} {
    200: Todo
    404: Error
    500: Error
}
```

**Comment by basdgrt** [comment]
Did you also consider the possibility of having an empty response? For example by having a default type `Unit`, or `Empty`?

Example:

```
endpoint DeleteTodo DELETE /todos/{id: Int} {
    204: Unit
    404: Error
}
```

**Comment by basdgrt** [comment]
Did you consider using a different syntax for the status code to response type mappings? On one hand it looks quite okay with the semicolon `:`.  On the other hand, I feel this is a different relationship than variable name and variable type.

How about something like this:

```
endpoint GetTodoById GET /todos/{id: Int}  {
    200 -> Todo
    404 -> Error
    500 -> Error
}
```

To be honest not quite sure which version I like more myself. But maybe some food for thought.
