### ISSUE TITLE
Intellij plugin not compatible with version 2024.1

### ISSUE THREAD

**Issue by nsmnds** [flock-community/wirespec#180]
After updating to Intellij 2024.1 there is an error which shows that the Wirespec plugin is not compatible:

<img width="396" alt="image" src="https://github.com/flock-community/wirespec/assets/5821618/a9357472-34f4-48e1-b17f-ead85147e802">

**Comment by wilmveel** [comment]
<img width="762" alt="image" src="https://github.com/flock-community/wirespec/assets/3841133/351e438d-aac5-4745-819b-7ceb63bc918a">
