### ISSUE TITLE
Loosen content-type check to allow MIME type parameters

### ISSUE THREAD

**Issue by nsmnds** [flock-community/wirespec#254]
I've noticed that the generated Wirespec response mapper handles the content type very strictly:

```
fun <B> RESPONSE_MAPPER(contentMapper: Wirespec.ContentMapper<B>) = { response: Wirespec.Response<B> ->
    when {
        response.status == 200 && response.content?.type == "application/json" -> ...
    }
}
```

It checks for an exact match. However, according to the specification (https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types), a MIME type can also have parameters, such as a charset. For example:  `application/json; charset=UTF-8`. 

The current implementation would lead to an error in the response mapper when encountering such a MIME type.

Is it possible to loosen the content-type check?

**Comment by jerrevanveluw** [comment]
We are dropping MIME_types altogether. This should not be a concern of wirespec and can be taken into account while mapping the requests/responses in your application. This should loosen up the check :)
